### ISSUE TITLE
Error during launching welderwire theme

### ISSUE THREAD

**Issue by mastermind1981** [weld-co/welderwire-theme#40]
Hello,

First of all, congratulation for your good job on the theme.

I got a problem while launching telescope with the theme : I'm using the 0.25.0 telescope (I have addFiles by addAssets in package.js the function does not accept images), when launching the application these errors shows in the console :

```

W20150930-14:49:00.318(1)? (STDERR)           
W20150930-14:49:00.319(1)? (STDERR) /Users/dev/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150930-14:49:00.319(1)? (STDERR)                         throw(ex);
W20150930-14:49:00.319(1)? (STDERR)                               ^
W20150930-14:49:00.350(1)? (STDERR) ReferenceError: Router is not defined
W20150930-14:49:00.350(1)? (STDERR)     at Settings.addField.fieldName (common/custom_routes.js:2:1)
W20150930-14:49:00.351(1)? (STDERR)     at /Users/dev/Desktop/akhbar/welder/.meteor/local/build/programs/server/packages/welderwire-theme.js:530:4
W20150930-14:49:00.351(1)? (STDERR)     at /Users/dev/Desktop/akhbar/welder/.meteor/local/build/programs/server/packages/welderwire-theme.js:986:3
W20150930-14:49:00.351(1)? (STDERR)     at /Users/dev/Desktop/akhbar/welder/.meteor/local/build/programs/server/boot.js:242:10
W20150930-14:49:00.351(1)? (STDERR)     at Array.forEach (native)
W20150930-14:49:00.352(1)? (STDERR)     at Function._.each._.forEach (/Users/dev/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150930-14:49:00.352(1)? (STDERR)     at /Users/dev/Desktop/akhbar/welder/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
```

Thank you

**Comment by jamiewilson** [comment]
Hey @mastermind1981, sorry about this. I haven't had a chance to update my theme the latest version of telescope. It should work with 0.23.0.

**Comment by mastermind1981** [comment]
Okay thank you i will test it with 0.23.0

**Comment by RyanKopinskyLLC** [comment]
Getting the same issue which is caused by the change from IronRouter to FlowRouter in Telescope. Any idea if you plan to update this theme moving forward?
